### PR TITLE
Updated hacking.md with a description of local development

### PR DESCRIPTION
**Pull request by soltysh**
@mfojtik @bparees PTAL

/fyi @Maxim-Filimonov

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh shouldn't be this more like 'CONTRIBUTING.md'?

**Comment by soltysh** [comment]
Yeah, maybe I'll just rename the file, I don't see a point in having two, @mfojtik makes sense?

**Comment by mfojtik** [comment]
:+1: 

Also the content LGTM.

**Comment by soltysh** [comment]
Done.

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
