### PR TITLE
Use docker TLS connection if available

### PR DESCRIPTION
**Pull request by csrwng**
This change updates the go-dockerclient dependency and allows STI to use TLS to communicate with Docker.

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees @soltysh fyi

**Comment by bparees** [comment]
lgtm.

**Comment by soltysh** [comment]
LGTM, but it looks your bump commit is missing `github.com/docker/docker/pkg/units`

**Comment by csrwng** [comment]
It's fixed. It was compiling ok in go 1.4, but not in 1.3. Is there any reason why we still want 1.3 for travis?

**Comment by soltysh** [comment]
I'm being compatible with origin, we can ask @smarterclayton for plans regarding that.

**Comment by csrwng** [comment]
@soltysh merge?

**Comment by soltysh** [comment]
[merge]

**Comment by soltysh** [comment]
@csrwng can you please update integration tests, based on following output:
```
Integration test cases ...

# github.com/openshift/source-to-image/test/integration
_output/local/go/src/github.com/openshift/source-to-image/test/integration/integration_test.go:174: unknown api.Request field 'DockerSocket' in struct literal
_output/local/go/src/github.com/openshift/source-to-image/test/integration/integration_test.go:229: unknown api.Request field 'DockerSocket' in struct literal
_output/local/go/src/github.com/openshift/source-to-image/test/integration/integration_test.go:251: unknown api.Request field 'DockerSocket' in struct literal
FAIL	github.com/openshift/source-to-image/test/integration [build failed]
```

**Comment by csrwng** [comment]
Fixed [test]

**Pull request merged**
