### PR TITLE
Card devexp_395, devexp_416 Added documentation for STI.

### PR DESCRIPTION
**Pull request by soltysh**
I added the cli docs and I did small flag cleaning:
* unified certain flags (namely `callbackUrl` -> `callbackURL` and `savetempdir` -> `saveTempDir`)
* added `forcePull` and `saveTempDir` to `usage` command, as these make sense there as well

@bparees @csrwng waiting for your comments.

### CODE REVIEW

**Comment by soltysh** [comment]
Addressed @mfojtik's [comment](https://github.com/openshift/ruby-20-centos/pull/7#discussion_r22587383).

**Comment by mfojtik** [comment]
LGTM

**Comment by soltysh** [comment]
Rebased on top of #98 & #103.

**Comment by soltysh** [comment]
[merge]

**Comment by soltysh** [comment]
Strange error, forcing [test]

**Comment by soltysh** [comment]
After successful test [merge] once again.

**Comment by soltysh** [comment]
I removed some spaces to see if it'll work.

**Pull request merged**
