### PR TITLE
tolerate #refs on file path git urls

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero ptal, this is needed to resolve the issue being seen in https://github.com/openshift/origin/pull/9678

**Comment by bparees** [comment]
[test]

**Comment by gabemontero** [comment]
IGTM

**Comment by gabemontero** [comment]
@gabemontero reviewing pr's on the iphone :-)

**Comment by bparees** [comment]
[merge]

**Pull request merged**
