### PR TITLE
Commit container with original builder user

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/source-to-image/issues/81

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]
(should probably get a test case at some point...)

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@mfojtik looks like you're hitting a timeout that needs to be bumped.

**Comment by mfojtik** [comment]
[merge]

it seems like the run test is flaky, I fixed the path where it stores logs so we can inspect them in Jenkins.

**Pull request merged**
