### PR TITLE
Change override entrypoint to /usr/bin/env

### PR DESCRIPTION
**Pull request by bparees**
@grahamdumpleton ptal. 

fixes https://github.com/openshift/source-to-image/issues/559
[test]

### CODE REVIEW

**Comment by bparees** [comment]
@php-coder ptal.

**Comment by php-coder** [comment]
LGTM.

BTW, maybe it would be good to mention this in the docs (for example, `docs/debugging-s2i.md`). As far I understand this case is rare, but as a user that will find it, I would like to have a bit info about this. For example, we could mention that S2I prefers images with `/usr/bin/env` and if user doesn't have such image, he could create a symlink.

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@php-coder it remains to be seen if this is the long term solution, there's still some discussion going on, so i'm not going to bother doc'ing it just yet.

**Comment by bparees** [comment]
@php-coder (discussion is here: https://github.com/openshift/source-to-image/issues/475#issuecomment-238088669)

**Pull request merged**
