### PR TITLE
Match origin deps

### PR DESCRIPTION
**Pull request by jim-minter**
This PR (a) pulls docker/engine-api *back* to match the current version in origin, including necessary fix-ups/reverts in our code
(b) pulls *forwards* other godeps to do the same.  After this PR we match in all godeps except glog (where s2i has latest, origin has a fork/hack, minor differences) and github.com/stevvooe/resumable (s2i has slightly more recent than origin - s2i's includes some go 1.7 fixes)

@PI-Victor

### CODE REVIEW

**Comment by jim-minter** [comment]
[test]

**Comment by bparees** [comment]
@jim-minter if i'm reading this right there were no actual s2i code changes required to switch the godep versions?

**Comment by jim-minter** [comment]
@baprees there were a couple, which I can split out if required.  (1) For rolling back the engine-api, I had to undo the few changes I made when rolling it forward + apply an upstream bugfix manually.  (2) For rolling forward github.com/docker/docker there was a one line change to pkg/build/strategies/onbuild/onbuild_test.go.

Specifically I wasn't sure how you want to handle case (1) or how you want the commit line written as it's a backwards bump.

**Comment by bparees** [comment]
@jim-minter generally we try to keep the godep changes in separate commits from the pkg code changes, so yeah if you can split those out it'd help.

**Comment by jim-minter** [comment]
@bparees done

**Comment by bparees** [comment]
lgtm [merge]

**Pull request merged**
