### PR TITLE
Disable Travis CI by removing the .travis.yml file

### PR DESCRIPTION
**Pull request by coreydaley**
Removing Travis CI
If there is something that Travis is doing here that we need I am happy to update the prow configuration to do it instead so that we can dump Travis CI.

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @gabemontero @bparees 
Ben, assigning to you since @adambkaplan is on PTO

**Comment by bparees** [comment]
/unassign

i don't know what coverage you guys have elsewhere at this point so i don't feel comfortable merging this

/assign @adambkaplan

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
