### PR TITLE
Show stderr from save-artifacts

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees @soltysh FYI (need to test this ;-)

**Comment by bparees** [comment]
lgtm

**Comment by soltysh** [comment]
LGTM, let's see the tests.
[test]

**Comment by mfojtik** [comment]
@soltysh can you please test this manually? I had no time for that today :(

**Comment by soltysh** [comment]
@mfojtik I'll do that first thing in the morning when dealing with the other error, I feel exhausted already.

**Comment by mfojtik** [comment]
@soltysh fixed... can you have a second look?

snippet:

```console
I0515 13:08:56.900774 25185 docker.go:301] Attaching to container
I0515 13:08:56.902612 25185 docker.go:354] Starting container
E0515 13:08:57.016167 25185 sti.go:416] before tar
I0515 13:08:57.104744 25185 tar.go:178] Creating /tmp/sti143720577/upload/artifacts/.bundle/config
I0515 13:08:57.104948 25185 tar.go:196] Extracting/writing /tmp/sti143720577/upload/artifacts/.bundle/config
I0515 13:08:57.105364 25185 tar.go:215] Done with /tmp/sti143720577/upload/artifacts/.bundle/config
I0515 13:08:57.105432 25185 tar.go:227] Done extracting tar stream
I0515 13:08:57.105443 25185 docker.go:364] Waiting for container
I0515 13:08:57.193554 25185 docker.go:370] Container exited

```

**Comment by soltysh** [comment]
Still LGTM.

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
