### PR TITLE
reference openshift image guidelines

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/source-to-image/issues/472

### CODE REVIEW

**Comment by bparees** [comment]
@alberttwong fyi.

**Comment by bparees** [comment]
[merge]

**Comment by alberttwong** [comment]
just curious.. how do you get this page from the readme.md?

**Comment by bparees** [comment]
@alberttwong it's linked in the "Anatomy of a builder image" section.  But i've pushed a change to hopefully make that more obvious.

**Comment by bparees** [comment]
[merge]

**Comment by alberttwong** [comment]
Yes... ideally, we'd have more people creating more s2i images.

**Pull request merged**
