### PR TITLE
Bump go version

### PR DESCRIPTION
**Pull request by danmcp**

### CODE REVIEW

**Comment by danmcp** [comment]
@soltysh @bparees You guys know what's going on with Travis:

hack/../hack/common.sh: line 416: STI_GIT_MAJOR: unbound variable

Note that:

$("${git[@]}" describe "${STI_GIT_COMMIT}^{commit}" 2>/dev/null)

is returning:

fatal: No annotated tags can describe '8791e3edfa1c9d19d48855d8151cbdf132e759c4'

**Comment by bparees** [comment]
No, I peeked at it last night and saw that until about a week ago Travis
was working, and nothing obvious was committed since, but that's as far as
i dug. Will spend some more time on it... Obviously it's not failing
outside of Travis.

Ben Parees | OpenShift

**Comment by soltysh** [comment]
Let's merge this as is (LGTM), we'll tackle travis down the road.

[merge]

**Comment by mfojtik** [comment]
@soltysh we should fix the unbound variable asap

**Comment by soltysh** [comment]
@mfojtik let us first have the build pieces in and I'll tackle the unbound variable afterwards.

**Pull request merged**
