### PR TITLE
error out on unparseable urls

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/source-to-image/issues/847

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal and tell me if you're surprised that `file://./path` is no longer properly parseable in golang (the "." gets treated as a hostname now).

**Comment by jim-minter** [comment]
lgtm: relative paths cannot be expressed in file:// URLs.

**Comment by bparees** [comment]
[merge]

**Comment by helio-frota** [comment]
good to know.
I'll test it [maybe tomorrow]
thanks!

**Pull request merged**
