### PR TITLE
use --tags for git-describe

### LINKED ISSUE #355: Wrong version in CLI
When I build the `v1.0.3` tag from source and I run `s2i version` I get: `s2i v1.0.1-99-g08e6631` which is kinda confusing :)

### PR DESCRIPTION
**Pull request by jmtd**
Fixes #355

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

@bparees we should fix the release binaries to have correct version

[merge]

**Comment by bparees** [comment]
@mfojtik i'm planning to do a new s2i release soon anyway, hoping to include @gabemontero's upcoming git clone fix first though.

**Comment by gabemontero** [comment]
@mfojtik @bparees I believe that fix is going to be origin only, if time is of the essence

**Comment by mfojtik** [comment]
@bparees I think we should still fix the binaries for 1.0.3 to report correct version :-)

**Comment by bparees** [comment]
@gabemontero it's not particularly urgent.  why is the fix origin only?  is it not broken for s2i?

**Comment by gabemontero** [comment]
@bparees roger that (urgency) - the problematic code path is unique to secret processing in the build config, which does not apply to s2i

**Comment by mfojtik** [comment]
@gabemontero @bparees how is that related to this issue? ;-)

**Comment by bparees** [comment]
@mfojtik it relates to when we're going to do a new release w/ proper versioning and whether it's worth re-doing the existing release or not.

**Comment by mfojtik** [comment]
@bparees I think it worth redoing the previous release. I think the only thing that is broken currently is the binary that we published (it is reporting wrong version). The tag is is properly, so we just need to upload a new binary built by ./hack/build-release.sh with this fix.

**Pull request merged**
