### PR TITLE
expose more failure specifics (incluidng OOMKilled) on run container …

### PR DESCRIPTION
**Pull request by gabemontero**
…failures

first step in addressing https://github.com/openshift/origin/issues/15032

@openshift/devex PTAL

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
also ... this used to be a thing way back when ... curious if it still works:

[test][openshift]

**Comment by bparees** [comment]
lgtm.  you've made golint unhappy though:
./pkg/docker/docker_test.go:365:3: struct field errJson should be errJSON

**Comment by gabemontero** [comment]
errJson -> errJSON pushed

**Comment by gabemontero** [comment]
bump @bparees if still gtm

**Comment by bparees** [comment]
[merge]

**Pull request merged**
