### PR TITLE
Improve Bash scripts

### PR DESCRIPTION
**Pull request by rhcarvalho**
Not really a love affair with Bash...

### CODE REVIEW

**Comment by rhcarvalho** [comment]
[test]

Time for some Bash "Spring Cleaning", @soltysh @bparees PTAL

**Comment by mfojtik** [comment]
@rhcarvalho same here, please remove :heart: from commit messages (and maybe make them more explicit). Changes looks good.

**Comment by soltysh** [comment]
LGTM, please squash also into one commit as well.

**Comment by mfojtik** [comment]
@rhcarvalho bump?

**Comment by bparees** [comment]
lgtm [merge]

**Pull request merged**
