### PR TITLE
Use the latest text version of the Apache 2.0 License

### PR DESCRIPTION
**Pull request by jawnsy**
This change simply replace the contents of the LICENSE with:

  curl https://www.apache.org/licenses/LICENSE-2.0.txt -o LICENSE

Signed-off-by: Jonathan Yu <jawnsy@redhat.com>

### CODE REVIEW

**Comment by bparees** [comment]
[merge]

**Comment by jawnsy** [comment]
Hmm... Is this a flake? Is the error about missing 'tar' normal?

```
I0101 03:06:04.712568    2052 sti.go:652] /bin/sh: tar: not found
I0101 03:06:04.712568    2052 tar.go:286] Adding to tar: C:\cygwin\tmp\s2i849937846\upload\scripts\run as scripts/run
I0101 03:06:04.713583    2052 docker.go:933] Removing container "cd332d030165c41ca0dfede5f73ed13afa485b83b5356a5355869cf847e81478" ...
I0101 03:06:05.100563    2052 docker.go:937] Removed container "cd332d030165c41ca0dfede5f73ed13afa485b83b5356a5355869cf847e81478"
I0101 03:06:05.100563    2052 cleanup.go:33] Removing temporary directory C:\cygwin\tmp\s2i849937846
I0101 03:06:05.100563    2052 fs.go:236] Removing directory 'C:\cygwin\tmp\s2i849937846'
--- FAIL: TestLayeredBuildNoTarNoName (1.94s)
	integration_test.go:335: An error occurred during the build: write tcp 172.18.2.6:49642->172.18.6.159:2376: wsasend: An established connection was aborted by the software in your host machine.
```

**Comment by bparees** [comment]
it's probably another issue w/ the windows testing @jim-minter added. we'll have to wait for post shutdown to look at this.

**Comment by jim-minter** [comment]
The error about missing 'tar' is expected.  The issue here is that for some reason the TCP docker connection between s2i and the RHEL box broke.  @bparees I don't know why this happened and I haven't seen this before.  Can we put this down to network glitch and see if it happens again?

**Comment by jim-minter** [comment]
[test]

**Comment by bparees** [comment]
>  Can we put this down to network glitch and see if it happens again?

sure.

[merge]

**Pull request merged**
