### PR TITLE
add seed to container name

### LINKED ISSUE #955: The container name is not rand.
Each time i run the cmd, i got the same container with suffix "9acb0442". It will make concurrent building failed, the erros is like "**s2i_centos_python_35_centos7_9acb0442 is already in use by container xxxxx**". We should set seed before generating container name. check <https://github.com/openshift/source-to-image/blob/1b34d86b72df25a14ed7adc658a6682ea25da180/pkg/docker/docker.go#L77>

### PR DESCRIPTION
**Pull request by magicsong**
fix #955

### CODE REVIEW

**Comment by bparees** [comment]
/assign @adambkaplan 
(lgtm though)

**Comment by adambkaplan** [comment]
[merge]

**Comment by adambkaplan** [comment]
[test]

**Comment by adambkaplan** [comment]
[merge]

**Comment by adambkaplan** [comment]
force-merged

**Pull request merged**
