### PR TITLE
Added missing OnBuild strategy tests

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@soltysh @bparees PTAL

Partially addressing https://github.com/openshift/origin/pull/1024#issuecomment-74756532

**Comment by mfojtik** [comment]
@bparees added tests for ContextDir as well.

**Comment by soltysh** [comment]
LGTM.

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
