### PR TITLE
remove ec2 instance suffixes

### LINKED ISSUE #793: Windows s2i instance naming breaks pruning script
https://github.com/openshift/source-to-image/blob/112f0d4fd5163e57b1d9414dabc81f905f38a212/hack/windows/Vagrantfile#L19

This line yields instances named like "`origin_test_pull_requests_s2i_windows_258-windows`". The suffix "`windows`" is redundant, and it breaks the verifier instance matching regexes in our pruning scripts - specifically this one: https://github.com/openshift/li/blob/9618207bcf5014071354ce591c4e90b04056b93a/build/dev_tools_constants.rb#L55 - which expect the build number to be at the very end of the instance name.

### PR DESCRIPTION
**Pull request by bparees**
fixes #793

### CODE REVIEW

**Comment by bparees** [comment]
@dobbymoodge @jim-minter ptal
[test]

**Comment by jim-minter** [comment]
Won't this bring up two different instances with the same name?  Doesn't sound like a good idea to me.  `"Name" => "rhel_#{ENV['USER']}"` is hacky but would it do instead?

**Comment by dobbymoodge** [comment]
huh, looks like the info isn't exactly redundant - this creates two VMs, blahblah-buildnum-rhel and blahblah-buildnum-windows. It looks like the code will need to be a little more complex; it might be best to put the additional info between the image name and the buildnum, which means splitting and reconstructing that string...

**Comment by dobbymoodge** [comment]
@jim-minter That also breaks the prune script, which is looking for something like `/origin_.*(\d+)/`

**Comment by dobbymoodge** [comment]
`s/^(.+)_(\d+)$/\1_rhel_\2/`

**Comment by jim-minter** [comment]
When running locally, it's improbable that the name will be of the form blahblah-buildnum - suggest that if it ends _\d+, then insert the text before the final _\d+, otherwise append as is currently.  Plus comment/link to this issue.

**Comment by dobbymoodge** [comment]
Maybe change the job definition to build `$USER` without the buildnum, and then do something like:
```
"Name" => "#{ENV['USER']}_rhel#{ENV['BUILDNUM'] ? "_#{ENV['BUILDNUM']}" : ""}"
```
or maybe construct that string beforehand so it doesn't look like code vomit.

**Comment by dobbymoodge** [comment]
```
rhel_user = "#{ENV['USER']}_rhel"
rhel_user += "_#{ENV['BUILDNUM']}" if ENV['BUILDNUM']
...
```

**Comment by bparees** [comment]
I was going off @dobbymoodge's issue report which indicated that the ec2 instance name already includes the job name anyway:

> This line yields instances named like "origin_test_pull_requests_s2i_windows_258-windows". 

(and presumably anyone running locally would run rhel OR windows as separate invocations, again passing a unique name to each)

**Comment by dobbymoodge** [comment]
@bparees looks like `vagrant up` with this vagrantfile will always bring up both kinds of VMs.

**Comment by bparees** [comment]
yeah i see that now.  Not really convinced it's a problem, though.  You get two instances w/ the same name, but that doesn't bother ec2 and once is clearly a rhel machine and the other is clearly a windows machine. [/shrug]

**Comment by bparees** [comment]
i guess it might cause the job some confusion when it goes to terminate things.

**Pull request closed without merging**
