### PR TITLE
Revert "Remove UseLogger"

### PR DESCRIPTION
**Pull request by bparees**
This reverts commit 65d46436ab599633b76e570311a05f46a818389b.

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik this change broke "s2i usage" invocations.

**Comment by bparees** [comment]
nm, looks like it was all  73dd2c2d0946e098a233f6ac56a4e2d91e22204d

**Comment by mfojtik** [comment]
@bparees you should rebase, I don't have this commit in my master :-) (I removed UseLogger)

**Comment by bparees** [comment]
@mfojtik commit 65d46436ab599633b76e570311a05f46a818389b absolutely exists in the source-to-image commit history:
https://github.com/openshift/source-to-image/commits/master

**Pull request closed without merging**
