### PR TITLE
Pull image before executing S2I script [1.5]

### PR DESCRIPTION
**Pull request by csrwng**
Backport of openshift/source-to-image#743 for 1.5

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal

**Comment by bparees** [comment]
lgtm.  manually merging since apparently the bot doesn't handle these.

**Comment by bparees** [comment]
@dobbymoodge @stevekuznetsov is it difficult to enable rosie for these other branches?

**Comment by stevekuznetsov** [comment]
No, I thought I had done that.

**Comment by stevekuznetsov** [comment]
Wait, this isn't the Jenkins repo. Let me look

**Comment by stevekuznetsov** [comment]
`[test]` and `[merge]` should work for all branches now on `openshift/source-to-image`

**Comment by bparees** [comment]
thanks @stevekuznetsov

**Pull request merged**
