### PR TITLE
Add --assemble-user option

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/source-to-image/issues/81

This allows to execute the assemble script under specified user.

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh @bparees PTAL

**Comment by soltysh** [comment]
I'd like to see an integration test for that use case, otherwise looks good.

**Comment by mfojtik** [comment]
@soltysh I can promise you I will add one, in future.

**Comment by soltysh** [comment]
Then merge will have to wait for the future :stuck_out_tongue_winking_eye:  But seriously this kind of functionality is easily breakable and adding the int test case right now is highly required, imho. But @bparees has the power to overrule my statement.

**Comment by mfojtik** [comment]
@soltysh this PR is just about passing the User down to RunContainerOpt and we have to verify that the User field is set properly which I do in the unit test. The integration test can run with different user, but it will not do too much and it would be hard to check if it really ran as that user ;-) (I can craft assemble that will store the output of `id -u`).

**Comment by soltysh** [comment]
> I can craft assemble that will store the output of id -u

That's all I'm asking for.

**Comment by mfojtik** [comment]
@soltysh we should simplify the integration tests to make it possible to do this easily. I can write that test, but it will make test integration more big and complex. We should brainstorm about how to make the integration simple.

**Comment by soltysh** [comment]
With #347 in mind, LGTM.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
