### PR TITLE
Removed pkg/test from excluded packages in script

### PR DESCRIPTION
**Pull request by oatmealraisin**
This allows us to use Git testing utilities in origin.

Perhaps in the future we should merge the Git utilities that are spread between the projects?

Sorry for the quick one-liners :)

### CODE REVIEW

**Comment by bparees** [comment]
hm.  this was just added by @php-coder a few days ago to prevent us pushing this code up to origin.

it does seem like it could be useful from within origin so i'm ok w/ merging it, but will let @php-coder weigh in first in case he sees a good reason not to.

**Comment by oatmealraisin** [comment]
It's only for the CreateLocalGitRepository() function, if that changes anything

**Comment by php-coder** [comment]
>hm. this was just added by @php-coder a few days ago to prevent us pushing this code up to origin.

In the PR https://github.com/openshift/source-to-image/pull/563 I excluded `pkg/docker/test` directory. `pkg/test` was in the script since the beginning. Let's merge it and see what happens then :)

**Comment by bparees** [comment]
[merge]

**Pull request merged**
