### PR TITLE
[#303] Fix empty additional topics in s2i help output

### PR DESCRIPTION
**Pull request by php-coder**
I've updated spf13/cobra (with all its dependencies) to the same version as we're using in origin.

Updated dependencies:
- github.com/spf13/pflag
- github.com/spf13/cobra

New dependencies:
- github.com/cpuguy83/go-md2man
- github.com/russross/blackfriday
- github.com/shurcooL/sanitized_anchor_name

Fix for #303

PATAL @rhcarvalho

### CODE REVIEW

**Comment by soltysh** [comment]
Godeps bumps needs to conform to the rules described [here](https://github.com/openshift/origin/blob/master/HACKING.md#updating-other-godeps-from-upstream). Each dep should be a separate commit. All the rest looks good.

**Comment by php-coder** [comment]
>Each dep should be a separate commit.

@soltysh But in this case I'll break the build because with new version of `spf13/cobra` doesn't build without `cpuguy83/go-md2man` and it won't build without `russross/blackfriday` that depends on `shurcooL/sanitized_anchor_name`. Do I still need to create separate commits?

**Comment by soltysh** [comment]
Yes please. Separate commits but in one PR. It's for having that info in
history.

**Comment by php-coder** [comment]
@soltysh Done. Thank you for a fast review!

**Comment by soltysh** [comment]
One tiny nit, replace ':' with a space please. I know I'm being picky it would be good to be consistent still. Otherwise LGTM.

**Comment by rhcarvalho** [comment]
@soltysh is it documented wrong in origin? https://github.com/openshift/origin/blob/master/HACKING.md#updating-other-godeps-from-upstream

**Comment by soltysh** [comment]
Hmm... now I am not sure.  Need to confirm that. Because the couple of
recent bumps in origin used version with space instead of colon.
@smarterclayton which form is the preferred?

**Comment by smarterclayton** [comment]
We use `bump(foo):bar` - colon.

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@php-coder can you please remove all files from the Godeps that are not Go files and leave just those that we actually import? I know that using godeps is pain, but we should at least keep the Godeps directory clean ;-)

**Comment by php-coder** [comment]
>can you please remove all files from the Godeps that are not Go files and leave just those that we actually import?

@mfojtik Yes, I can. A couple of questions if you don't mind: 1) is it documented somewhere? 2) should I keep `LICENSE`/`README.md` files? 3) May be there is a special way of determining a set of go files that we are importing and their dependencies?

**Comment by mfojtik** [comment]
@php-coder the original way is to do `godep restore` and `godep save` which will only copy the files (packages) you import, nothing else. But because that is pain, we often just copy the files/directories over... You don't need to keep the LICENSE/README.md afaik (I don't think godeps does that).

**Comment by php-coder** [comment]
@mfojtik I've updated my commits. I've just removed non-go files. May be I also should delete `_test.go` files?

**Comment by mfojtik** [comment]
@php-coder yes, they are not imported with the package.

**Comment by php-coder** [comment]
@mfojtik Ok, I've removed also test files (btw, other dependencies still have non-go files and tests).

**Comment by soltysh** [comment]
@mfojtik actually if you have a look at origins' Godeps you'll see them as well, just fyi :wink:

**Comment by mfojtik** [comment]
@soltysh that does not mean it is correct, it means we are lazy in origin to clean them up :-)

**Comment by mfojtik** [comment]
[merge]

**Pull request merged**
