### PR TITLE
Parse $USER and set VM name accordingly

### LINKED ISSUE #793: Windows s2i instance naming breaks pruning script
https://github.com/openshift/source-to-image/blob/112f0d4fd5163e57b1d9414dabc81f905f38a212/hack/windows/Vagrantfile#L19

This line yields instances named like "`origin_test_pull_requests_s2i_windows_258-windows`". The suffix "`windows`" is redundant, and it breaks the verifier instance matching regexes in our pruning scripts - specifically this one: https://github.com/openshift/li/blob/9618207bcf5014071354ce591c4e90b04056b93a/build/dev_tools_constants.rb#L55 - which expect the build number to be at the very end of the instance name.

### PR DESCRIPTION
**Pull request by dobbymoodge**
Fixes #793

### CODE REVIEW

**Comment by dobbymoodge** [comment]
[test]

**Comment by dobbymoodge** [comment]
HT @bparees, @jim-minter PTAL

**Comment by dobbymoodge** [comment]
Looking better: 
image

**Comment by dobbymoodge** [comment]
Also the regex handles the new names correctly:
```
[46] pry(main)> 'origin_test_pull_requests_s2i_windows-rhel-270' =~ /^(origin).*[_-](\d+)$/
=> 0
[47] pry(main)> puts $1, $2
origin
270
=> nil
[48] pry(main)> 
```

**Comment by bparees** [comment]
lgtm, thanks @dobbymoodge 
[merge]

**Pull request merged**
