### PR TITLE
Add {linux,darwin}/aarch64 to cross-compile platforms.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/openshift/source-to-image/issues/1077.

@adambkaplan ptal.

### CODE REVIEW

**Comment by tmds** [comment]
@adambkaplan CI looks happy. Is this good to merge?

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by adambkaplan** [comment]
@tmds looks good, thank you for the PR!

**Pull request merged**
