### PR TITLE
Set entrypoint to /bin/env

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/source-to-image/issues/475

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

@GrahamDumpleton @bparees PTAL

**Comment by bparees** [comment]
lgtm [merge]

(we'll want to do a bump to origin of course)

**Comment by mfojtik** [comment]
@bparees will wait for https://github.com/openshift/source-to-image/pull/471 and then do a bump :-) we can do some minor release as well.

**Comment by soltysh** [comment]
@mfojtik out of curiosity can't we set entrypoint to be run, but only when one is set? I dislike the `/bin/env`, somehow...

**Comment by mfojtik** [comment]
@soltysh we can't as we chain commands there (we pipe tar, doing magic with injections, etc..) I tried /bin/sh and other things but /bin/env works the best...

**Comment by soltysh** [comment]
@mfojtik thx :smile:

**Pull request merged**
