### PR TITLE
Fix arguments length for sti rebuild

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
Without this fix, `sti rebuild` outputs this error https://paste.fedoraproject.org/256563/

**Comment by bparees** [comment]
lgtm [merge]

**Comment by soltysh** [comment]
@mfojtik isn't this fix related to #257 ?

**Comment by mfojtik** [comment]
@soltysh most likely yes :-)

**Comment by bparees** [comment]
I don't think so. This was just a failure if you ran with no args. It
shouldn't change behavior for with args.

I mean related in that it's parameter processing for rebuild I suppose, but
probably not beyond that?

Ben Parees | OpenShift

**Pull request merged**
