### PR TITLE
Make go routines in RunContainer safer when attaching to container

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@goldmann is testing this now. This is the only place in STI code where we do have 'wg.Wait()' so if it hangs in STI then this is the place...

**Comment by mfojtik** [comment]
@bparees checkout https://github.com/openshift/source-to-image/commit/7c2573bab40dc9269c37fb0d49fd8b60f5711e82 -> making STI more friendly for Java developers :-)

**Comment by bparees** [comment]
lgtm, but squash :)

**Comment by mfojtik** [comment]
@bparees those two commits are 2 separate things :)

**Comment by bparees** [comment]
@mfojtik then it should be 2 pulls :)

[merge]

**Comment by mfojtik** [comment]
@bparees 

```console
Running STI_TIMEOUT="--timeout 240s" hack/test-integration.sh...
You do not have necessary test images, be sure to run 'hack/build-test-images.sh' beforehand
```

**Comment by mfojtik** [comment]
[merge] again?

**Pull request merged**
