### PR TITLE
bump(github.com/golang/glog) 44145f04b68cf362d9c4df2182967c2275eaefed

### PR DESCRIPTION
**Pull request by jim-minter**
after this and https://github.com/openshift/origin/pull/12089, openshift and s2i godeps will actually match eachother.

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]

**Comment by bparees** [comment]
[merge]

**Comment by jim-minter** [comment]
@bparees is it possible this failed because you tagged 1.1.4 and not v1.1.4?

**Comment by bparees** [comment]
good catch, could be.

**Comment by bparees** [comment]
tags fixed
[merge]

**Comment by bparees** [comment]
well, that doesn't seem to have been it.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
