### PR TITLE
Disable non-GIT repo warning when quiet option

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
Fixes: https://github.com/openshift/source-to-image/issues/251

**Comment by mfojtik** [comment]
@soltysh @bparees @jhadvig review please

**Comment by bparees** [comment]
Does this need 3 reviewers? :) 
[merge]

**Comment by mfojtik** [comment]
@bparees it is pretty serious patch :)

**Pull request merged**
