### PR TITLE
handle empty docker auths cleanly

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/source-to-image/issues/640

@jim-minter ptal

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
(longer term we should probably be removing this custom parser logic and using the docker engine library assuming it has something appropriate.  we're using fsouza/go-dockerclient to handle this in origin)

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@oatmealraisin ptal

**Comment by bparees** [comment]
@coreydaley ptal

**Comment by coreydaley** [comment]
@bparees lgtm

**Comment by bparees** [comment]
[merge]

**Comment by jim-minter** [comment]
@bparees fyi I never got an e-mail notification for your 'ptal' message and github didn't cc me on the issue, hence the radio silence!

**Comment by jim-minter** [comment]
> (longer term we should probably be removing this custom parser logic and using the docker engine library assuming it has something appropriate. we're using fsouza/go-dockerclient to handle this in origin)

Maybe; actually I had a look at this a while back.  There are two principal problems:
1) upstream, docker has rather moved from .dockercfg files to preferring config.json files, and origin especially has a fair amount of logic centred around .dockercfg files which may be troublesome to adjust.  That bridge may need to be crossed at some point, but for now I thought it added churn for little value.
2) the docker client library code doesn't expose methods for reading in arbitrary .dockercfg files (it looks for $DOCKER_CONFIG/config.json first, then $HOME/.docker/.dockercfg as a fallback). Reading an arbitrary .dockercfg is currently allowed as a s2i command line switch and is also used by Origin through our API, and all of that would need to be deprecated / reworked as well.

**Comment by jim-minter** [comment]
belatedly, fwiw, perhaps this is worth a test case.

**Comment by bparees** [comment]
> fyi I never got an e-mail notification for your 'ptal' message and github didn't cc me on the issue, hence the radio silence!

weird.  github must be censoring me.

Thanks for the background on utility logic for parsing the various dockerconfig formats.  I guess we'll leave it as is for now.

Agreed that it's worthy of a TC.

**Pull request merged**
