### PR TITLE
Updating release code to use go1.18

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by omajid** [comment]
This reverted https://github.com/openshift/source-to-image/pull/1080. Is there any plan to re-enable it?

**Comment by coreydaley** [comment]
Those images would not build.

**Comment by omajid** [comment]
cc @tmds who initially contributed https://github.com/openshift/source-to-image/pull/1080

**Comment by tmds** [comment]
In don't speak Go, in https://github.com/openshift/source-to-image/pull/1080 I literally did what I was told to do [here](https://github.com/openshift/source-to-image/issues/1077#issuecomment-963400844).

@coreydaley would there be a way to acquire aarch64 builds of s2i?
This gets shipped in containers for OpenShift, doesn't it?

**Comment by tmds** [comment]
I think OpenShift uses [this image](https://catalog.redhat.com/software/containers/ocp-tools-4-tech-preview/source-to-image-rhel8/5f059b8d2991b4207fcdb1f4) (or one like it). It's available for x64, amd64, ppc64le and s390x.

@omajid if there is no (easy) way to get an aarch64 build, we could use this image.

**Pull request merged**
