### PR TITLE
report actual error on commit failure

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng @mfojtik ptal, we were masking the actual commit error since we don't expose the Details up the stack anywhere, which makes this issue impossible to debug:
https://github.com/openshift/origin/issues/8737

**Comment by csrwng** [comment]
LGTM

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
lgtm, nice catch

**Pull request merged**
