### PR TITLE
bump(*): Update transient dependency go-ansiterm

### PR DESCRIPTION
**Pull request by isutton**
The following error happens when executing `hack/build-cross.sh`:

```
./build-cross.sh
++ Building go targets for linux/amd64: cmd/s2i
++ Building go targets for darwin/amd64: cmd/s2i
++ Building go targets for windows/amd64: cmd/s2i
# github.com/docker/docker/pkg/term
../vendor/github.com/docker/docker/pkg/term/term_windows.go:35:44: undefined: winterm.ENABLE_VIRTUAL_TERMINAL_INPUT
../vendor/github.com/docker/docker/pkg/term/term_windows.go:48:44: undefined: winterm.ENABLE_VIRTUAL_TERMINAL_PROCESSING
../vendor/github.com/docker/docker/pkg/term/term_windows.go:48:87: undefined: winterm.DISABLE_NEWLINE_AUTO_RETURN
../vendor/github.com/docker/docker/pkg/term/term_windows.go:51:36: undefined: winterm.ENABLE_VIRTUAL_TERMINAL_PROCESSING
../vendor/github.com/docker/docker/pkg/term/term_windows.go:58:44: undefined: winterm.ENABLE_VIRTUAL_TERMINAL_PROCESSING
../vendor/github.com/docker/docker/pkg/term/term_windows.go:58:87: undefined: winterm.DISABLE_NEWLINE_AUTO_RETURN
../vendor/github.com/docker/docker/pkg/term/term_windows.go:61:36: undefined: winterm.ENABLE_VIRTUAL_TERMINAL_PROCESSING
../vendor/github.com/docker/docker/pkg/term/term_windows.go:172:40: undefined: winterm.DISABLE_NEWLINE_AUTO_RETURN
../vendor/github.com/docker/docker/pkg/term/term_windows.go:202:11: undefined: winterm.ENABLE_VIRTUAL_TERMINAL_INPUT
```

This happens because a previous PR, Docker has been updated but produced an error when cross compiling to Windows; to mitigate that, the `go-ansiterm` version has been bumped to the specific version obtained from https://github.com/moby/moby/commit/dbe4a30928d418e0570891a09703bcbc0e4997a1#diff-4061fcef378a6d912e14e2ce162a1995L2.

### CODE REVIEW

**Comment by sbose78** [comment]
Works for me, thanks!
```
sbose-mac:source-to-image sbose$ ./hack/build-cross.sh 
++ Building go targets for linux/amd64: cmd/s2i
++ Building go targets for darwin/amd64: cmd/s2i
++ Building go targets for windows/amd64: cmd/s2i
++ Building go targets for linux/386: cmd/s2i
++ Placing binaries
++ Creating source-to-image-v1.2.0-38-gb178763a-b178763a-linux-amd64.tar.gz
++ Creating source-to-image-v1.2.0-38-gb178763a-b178763a-darwin-amd64.tar.gz
++ Creating source-to-image-v1.2.0-38-gb178763a-b178763a-windows-amd64.zip
++ Creating source-to-image-v1.2.0-38-gb178763a-b178763a-linux-386.tar.gz
./hack/build-cross.sh took 38 seconds
```

Should add it to our CI in future.

**Comment by sbose78** [comment]
/lgtm
/approve

CC @adambkaplan

**Comment by adambkaplan** [comment]
:shakes fist at moby for not using go.mod:

Thanks @isutton for catching this!

/lgtm

**Pull request merged**
