### PR TITLE
bump(github.com/fsouza/go-dockerclient) 3213df8880de560ee41e30dbc6605…

### PR DESCRIPTION
**Pull request by bparees**
…eb04b1f80a4

fixes https://github.com/openshift/source-to-image/issues/520

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@gabemontero you might as well sign off on this one since it might cause you some pain (sorry).  might fix some stuff too though.

there were some major changes in the fsouza dependency packaging which is why this is a massive changeset.  (or i screwed up badly using godep)

**Comment by gabemontero** [comment]
yeah i think the pain is going to be unavoidable wrt moving off fsouza at this point @bparees :-)

can't guarantee delivery of the shift to k8s / engine-api is going to be immediate based on testing so far (i'll detail in scrum tomorrow), so doing what is needed for the customer issue makes sense ... i'll adjust later

igtm

**Comment by bparees** [comment]
[merge]

**Pull request merged**
