### PR TITLE
include directories in tar files

### PR DESCRIPTION
**Pull request by jim-minter**
Bug 1461503

### CODE REVIEW

**Comment by jim-minter** [comment]
[test]

**Comment by bparees** [comment]
lgtm.  Note that @mfojtik was correct about git ignoring empty dirs (during cloning I guess) so if you're an s2i cli user who's building from a repo, you'll need to specify "--copy" to use filecopy semantics instead of git clone semantics, or you'll lose your emptydirs during the clone.

but i tested this with --copy and my emptydirs were preserved in the resulting image.

thanks @jim-minter 

[merge]

**Comment by bparees** [comment]
failure cause:
```
--- FAIL: TestCreateTarStreamIncludeParentDir (0.00s)
	tar_test.go:119: Dir "testtar070815338/dir01/dir03" from tar "/tmp/testtarout745484481" does not match expected mode. Expected: -rwxrwxr-x, actual: -rwxr-xr-x
--- FAIL: TestCreateTar (0.00s)
	tar_test.go:119: Dir "dir01/dir03" from tar "/tmp/tar473899163" does not match expected mode. Expected: -rwxrwxr-x, actual: -rwxr-xr-x
	tar_test.go:119: Dir "link" from tar "/tmp/tar473899163" does not match expected mode. Expected: -rwxrwxr-x, actual: -rwxr-xr-x
--- FAIL: TestCreateTarIncludeDotGit (0.00s)
	tar_test.go:119: Dir "dir01/dir03" from tar "/tmp/tar281014149" does not match expected mode. Expected: -rwxrwxr-x, actual: -rwxr-xr-x
	tar_test.go:119: Dir "link" from tar "/tmp/tar281014149" does not match expected mode. Expected: -rwxrwxr-x, actual: -rwxr-xr-x
--- FAIL: TestCreateTarEmptyRegexp (0.00s)
	tar_test.go:119: Dir "dir01/dir03" from tar "/tmp/tar330543615" does not match expected mode. Expected: -rwxrwxr-x, actual: -rwxr-xr-x
	tar_test.go:119: Dir "link" from tar "/tmp/tar330543615" does not match expected mode. Expected: -rwxrwxr-x, actual: -rwxr-xr-x
ERROR: Error extracting tar stream
FAIL
```

**Comment by jim-minter** [comment]
@bparees all good with me, please merge if happy
(I had been expecting to find test errors especially on the Windows build, which is why I didn't assign the PR to you before)

**Comment by bparees** [comment]
[merge]

**Pull request merged**
