### PR TITLE
s2i: intermittent hang

### PR DESCRIPTION
**Pull request by gabemontero**
Bug 1368074
Bugzilla link https://bugzilla.redhat.com/show_bug.cgi?id=1368074
Detailed explanation
A timing window existed, seen first with incremental builds and the new engine-api/k8s docker client, where the attach container would never return because of a blocking channel call

@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]

**Comment by gabemontero** [comment]
I only got the known flake (the layered one, right?) when i ran the integration tests but the incremental builds had a couple of couldn't find the save-artifacts invoked markers.  Perhaps rather than a `case default:` in the change we do a timer in case we are exiting too soon.  I'll look into it either later this weekend or on Monday.

**Comment by gabemontero** [comment]
[test]

@bparees I reworked the fix, backing out the change to the borrowed k8s logic.  While that change handled the hang encountered, it did not properly account for stdin closing well before stdout did.

The new fix backs off the mutex.Lock/Unlock usage (too all or nothing in hindsight), and uses the fact that we have already moved past the container wait return (meaning we can assume the container has exited) and simply waits for the attach to have actually exited, or for a time out to expire.

If we don't see any data race errors flagged in the unit test, nor missing incremental output in the integration tests, we should be good to go.

**Comment by gabemontero** [comment]
OK, tests are clean.  @bparees - see if you are good with the new form of the fix, post comments / merge tag at your discretion please.

**Comment by bparees** [comment]
lgtm [merge]

**Pull request merged**
