### PR TITLE
Refactor runContainerTar method

### PR DESCRIPTION
**Pull request by php-coder**
I've refactored `runContainerTar()` by extracting 3 methods from it and inlining original one.

Despite this is just refactoring it's a part of the logic for running the containers and it's important to have this code more readable and understandable. I believe that after my refactoring, the code became easy to read/modify (at least for me :-D).

PTAL @bparees @rhcarvalho 
CC @mfojtik

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, needs squash
[test]

**Comment by php-coder** [comment]
Ready to merge.

**Comment by bparees** [comment]
[merge]

**Comment by rhcarvalho** [comment]
@php-coder awesome, thanks!

**Pull request merged**
