### PR TITLE
Apply .s2iignore during copy from local directory

### LINKED ISSUE #867: Apply .s2iignore for files that are copied as part of `--copy`
Hitting a bit of an edge case but hopefully there's an easy-ish fix for the copy step.

From reading [pkg/ignore/ignore.go](https://github.com/openshift/source-to-image/blob/57a644844c76dad4d42b7045e47e6b73e66d58d7/pkg/ignore/ignore.go#L21-L53) it seems that the way this happens right now is:

1. copy the source (or clone in the case of not `--copy`)
2. delete files in `.s2iignore`

I'm dealing with a particularly circular case where I'm attempting to build a docker image for a vagrant setup, while using vagrant to run s2i.  In short, the current build is trying to copy the vagrant image while inside of vagrant despite being in the `.s2iignore` -- this unsurprisingly fills up the disks.

The ideal case for me would be to apply the `.s2iignore` as a blacklist _during copying_ -- if this sounds acceptable I'd be willing to hack on a PR for this :)

### PR DESCRIPTION
**Pull request by nabilbendafi**
- Fixes #867

### CODE REVIEW

**Comment by adambkaplan** [comment]
/ok-to-test

Apologies it's taken us so long to loop back on this.

**Comment by adambkaplan** [comment]
I recommend adding an integration test to verify the behavior of .s2iignore:  https://github.com/openshift/source-to-image/blob/master/test/integration/integration_test.go

**Comment by nabilbendafi** [comment]
I tried to add an integration test that covers absence and presence of  _.s2iignore_ file

<details> 
  <summary>TestDockerfileLocalSource test result</summary>
<p>

```bash
=== RUN   TestDockerfileLocalSource
I0430 22:30:00.089572   24463 scm.go:20] DownloadForSource file:////tmp/s2i-dockerfiletest-dir514413533
I0430 22:30:00.089666   24463 download.go:38] Copying sources from "//tmp/s2i-dockerfiletest-dir514413533" to "/tmp/s2i-dockerfiletest-dir303889816/upload/src"
I0430 22:30:00.089735   24463 ignore.go:66] .s2iignore file does not exist
I0430 22:30:00.089886   24463 fs.go:252] D "/tmp/s2i-dockerfiletest-dir514413533/foo" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo"
I0430 22:30:00.090062   24463 fs.go:270] F "/tmp/s2i-dockerfiletest-dir514413533/foo/a_file" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/a_file"
I0430 22:30:00.090198   24463 fs.go:252] D "/tmp/s2i-dockerfiletest-dir514413533/foo/baz" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/baz"
I0430 22:30:00.090370   24463 fs.go:252] D "/tmp/s2i-dockerfiletest-dir514413533/foo/baz/foobar" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/baz/foobar"
I0430 22:30:00.090575   24463 fs.go:270] F "/tmp/s2i-dockerfiletest-dir514413533/foo/baz/foobar/a_file" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/baz/foobar/a_file"
I0430 22:30:00.090725   24463 fs.go:252] D "/tmp/s2i-dockerfiletest-dir514413533/foo/bar" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar"
I0430 22:30:00.090953   24463 fs.go:270] F "/tmp/s2i-dockerfiletest-dir514413533/foo/bar/another_file" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar/another_file"
I0430 22:30:00.091155   24463 fs.go:270] F "/tmp/s2i-dockerfiletest-dir514413533/foo/bar/a_file" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar/a_file"
I0430 22:30:00.091368   24463 ignore.go:66] .s2iignore file does not exist
I0430 22:30:00.091430   24463 dockerfile.go:115] Constructing image build context directory at /tmp/s2i-dockerfiletest-dir303889816/
I0430 22:30:00.091583   24463 dockerfile.go:474] No user environment provided (no environment file found in application sources)
I0430 22:30:00.091633   24463 dockerfile.go:214] Processing injected inputs: api.VolumeList(nil)
I0430 22:30:00.091663   24463 dockerfile.go:216] Processed injected inputs: api.VolumeList(nil)
I0430 22:30:00.091767   24463 dockerfile.go:287] Wrote custom Dockerfile to /tmp/s2i-dockerfiletest-dir303889816/Dockerfile
I0430 22:30:00.095532   24463 scm.go:20] DownloadForSource file:////tmp/s2i-dockerfiletest-dir514413533
I0430 22:30:00.095619   24463 download.go:38] Copying sources from "//tmp/s2i-dockerfiletest-dir514413533" to "/tmp/s2i-dockerfiletest-dir303889816/upload/src"
I0430 22:30:00.095693   24463 ignore.go:84] .s2iignore lists a file spec of dummy 
I0430 22:30:00.095729   24463 ignore.go:116] using globspec /tmp/s2i-dockerfiletest-dir514413533/dummy 
I0430 22:30:00.095769   24463 ignore.go:84] .s2iignore lists a file spec of foo/bar/another_file 
I0430 22:30:00.095808   24463 ignore.go:116] using globspec /tmp/s2i-dockerfiletest-dir514413533/foo/bar/another_file 
I0430 22:30:00.095851   24463 ignore.go:122] Glob result /tmp/s2i-dockerfiletest-dir514413533/foo/bar/another_file 
I0430 22:30:00.095891   24463 ignore.go:84] .s2iignore lists a file spec of foo/baz/foobar 
I0430 22:30:00.095938   24463 ignore.go:116] using globspec /tmp/s2i-dockerfiletest-dir514413533/foo/baz/foobar 
I0430 22:30:00.095995   24463 ignore.go:122] Glob result /tmp/s2i-dockerfiletest-dir514413533/foo/baz/foobar 
I0430 22:30:00.096374   24463 fs.go:270] F "/tmp/s2i-dockerfiletest-dir514413533/.s2iignore" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/.s2iignore"
I0430 22:30:00.096702   24463 fs.go:252] D "/tmp/s2i-dockerfiletest-dir514413533/foo" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo"
I0430 22:30:00.097064   24463 fs.go:270] F "/tmp/s2i-dockerfiletest-dir514413533/foo/a_file" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/a_file"
I0430 22:30:00.097390   24463 fs.go:252] D "/tmp/s2i-dockerfiletest-dir514413533/foo/baz" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/baz"
I0430 22:30:00.097720   24463 fs.go:249] Directory "/tmp/s2i-dockerfiletest-dir514413533/foo/baz/foobar" ignored
I0430 22:30:00.098014   24463 fs.go:252] D "/tmp/s2i-dockerfiletest-dir514413533/foo/bar" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar"
I0430 22:30:00.098405   24463 fs.go:267] File "/tmp/s2i-dockerfiletest-dir514413533/foo/bar/another_file" ignored
I0430 22:30:00.098603   24463 fs.go:270] F "/tmp/s2i-dockerfiletest-dir514413533/foo/bar/a_file" -> "/tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar/a_file"
I0430 22:30:00.099096   24463 ignore.go:84] .s2iignore lists a file spec of dummy 
I0430 22:30:00.099185   24463 ignore.go:116] using globspec /tmp/s2i-dockerfiletest-dir303889816/upload/src/dummy 
I0430 22:30:00.099291   24463 ignore.go:84] .s2iignore lists a file spec of foo/bar/another_file 
I0430 22:30:00.099368   24463 ignore.go:116] using globspec /tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar/another_file 
I0430 22:30:00.099533   24463 ignore.go:122] Glob result /tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar/another_file 
I0430 22:30:00.099613   24463 ignore.go:84] .s2iignore lists a file spec of foo/baz/foobar 
I0430 22:30:00.099677   24463 ignore.go:116] using globspec /tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/baz/foobar 
I0430 22:30:00.099729   24463 ignore.go:122] Glob result /tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/baz/foobar 
I0430 22:30:00.099766   24463 ignore.go:45] attempting to remove file /tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/bar/another_file 
I0430 22:30:00.099798   24463 ignore.go:45] attempting to remove file /tmp/s2i-dockerfiletest-dir303889816/upload/src/foo/baz/foobar 
I0430 22:30:00.099897   24463 dockerfile.go:115] Constructing image build context directory at /tmp/s2i-dockerfiletest-dir303889816/
I0430 22:30:00.100044   24463 dockerfile.go:474] No user environment provided (no environment file found in application sources)
I0430 22:30:00.100094   24463 dockerfile.go:214] Processing injected inputs: api.VolumeList(nil)
I0430 22:30:00.100123   24463 dockerfile.go:216] Processed injected inputs: api.VolumeList(nil)
I0430 22:30:00.100225   24463 dockerfile.go:287] Wrote custom Dockerfile to /tmp/s2i-dockerfiletest-dir303889816/Dockerfile
--- PASS: TestDockerfileLocalSource (0.01s)
PASS
coverage: 0.0% of statements
ok  	github.com/openshift/source-to-image/test/integration	(cached)	coverage: 0.0% of statements

Complete
```
</p>
</details>

**Comment by adambkaplan** [comment]
[TEST]

**Comment by adambkaplan** [comment]
/hold

@nabilbendafi fyi this is a component used by OpenShift. We are currently in a freeze period as we get ready for our 4.1 release. Once we are past code freeze I will be able to merge in.

**Comment by adambkaplan** [comment]
/lgtm

(don't have ci-operator yet to merge)

**Comment by adambkaplan** [comment]
@bparees you may need to start the merge

**Comment by bparees** [comment]
[merge]

Ben Parees | OpenShift

**Pull request merged**
