### PR TITLE
make status messages compliant with origin

### PR DESCRIPTION
**Pull request by PI-Victor**
also other formatting options for newfailure reason
[test]

### CODE REVIEW

**Comment by PI-Victor** [comment]
re[test]

**Comment by PI-Victor** [comment]
re[test]

**Comment by bparees** [comment]
i'm able to pull registry.access.redhat.com/openshift3/php-55-rhel7:latest now, so trying again
[test]

**Comment by PI-Victor** [comment]
@bparees tried the same when it failed the second time. seems rather strange

**Comment by bparees** [comment]
[merge]

**Pull request merged**
