### PR TITLE
Revert "Git spec handling revamp - backport to 3.6.0"

### PR DESCRIPTION
**Pull request by bparees**
Reverts openshift/source-to-image#779

we need to revert this for now because we're not prepared to make the required changes in the openshift 3.6 stream.

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal. after this merges i'll restart the process of bumping ocp 3.6

**Comment by jim-minter** [comment]
lgtm :cry:

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
