### PR TITLE
Updated release procedure, added description of that to HACKING.md

### PR DESCRIPTION
**Pull request by soltysh**
@mfojtik @bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
squash.

**Comment by soltysh** [comment]
Done.

**Comment by bparees** [comment]
I really don't have the mental capacity to parse this much shell scripting right now, but if you say it works i'm willing to take your word on it.  Definitely appreciate the docs.

**Comment by soltysh** [comment]
@bparees as usual, that's the origin version striped to fit STI :wink: I'll wait for @mfojtik opinion on this.

**Comment by bparees** [comment]
I assumed as much :)

**Comment by mfojtik** [comment]
LGTM

**Comment by soltysh** [comment]
[merge]

**Pull request merged**
