### PR TITLE
Add ppc64le support

### PR DESCRIPTION
**Pull request by Siddhesh-Ghadi**
Add ppc64le support for ci job on travis-ci.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/ok-to-test

@gabemontero @coreydaley @otaviof I don't see an issue adding Power to the list of supported arches, as I believe the release script generates ppc64le binaries for Linux. Down the road we can consider adding an integration suite to run on Power if/when the OpenShift on Power CI systems are open to the entire org.

**Comment by ghatwala** [comment]
@adambkaplan - thanks for the review here , would be good to have `ppc64le` tarball showing up in releases post this PR merger 👍 .

**Pull request merged**
