### PR TITLE
Always display source downloading message

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees FYI (will rebase to origin + do the same for docker strategy)

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@mfojtik pretty sure we handle cloning source differently in origin now, right?  I don't think this method gets invoked.

**Comment by mfojtik** [comment]
@bparees hmm I think you're right. going to check.

**Pull request merged**
