### PR TITLE
Bump dockerclient to match version in origin

### PR DESCRIPTION
**Pull request by rhcarvalho**
I'm gonna need code that is in the version in origin and not in the old version we had here (`AttachToContainerNonBlocking`)

Sending as separate PR to not pollute the diff of #430 with all these changes.

@bparees ptal

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]

**Comment by rhcarvalho** [comment]
@bparees I've updated the commit making sure the patch is the same as what's here:
https://github.com/fsouza/go-dockerclient/compare/25bc220b299845ae5489fd19bf89c5278864b050...0099401a7342ad77e71ca9f9a57c5e72fb80f6b2.

Actually not a must-have for my other PR... I thought we were dealing with a relatively older version (coming from the bad assumption of what I've seen last time).

**Comment by bparees** [comment]
312 files down to 6.... do i want to know what happened the first time around? :)

[merge]

**Comment by rhcarvalho** [comment]
> do i want to know what happened the first time around? :)

I want to know too :)

No way to trust `godep`...

**Pull request merged**
