### PR TITLE
bug_1185730

### PR DESCRIPTION
**Pull request by csrwng**
https://bugzilla.redhat.com/show_bug.cgi?id=1185730

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees @soltysh - this is a way to fix this issue. It's definitely not the only way... I'd like to hear what you think.

**Comment by bparees** [comment]
looks like a nice clean solution to me.

**Comment by csrwng** [comment]
Changed COPY to ADD, and added a TODO to take into consideration images that may not have chown in them.

**Comment by csrwng** [comment]
@smarterclayton @bparees pls review

**Comment by bparees** [comment]
so we're broken for images that do not contain tar and do use a non-root user, for now?

**Comment by csrwng** [comment]
correct. With this fix we will not be broken as long as the image contains 'chown'

**Comment by bparees** [comment]
lgtm.

**Comment by csrwng** [comment]
merge?

**Comment by smarterclayton** [comment]
[merge]

**Pull request merged**
