### PR TITLE
Issue183 - migrated STI_SCRIPTS_URL to labels

### PR DESCRIPTION
**Pull request by soltysh**
This PR will address @183.

@mfojtik @smarterclayton @bparees PTAL.

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh copy the files from go-dockerclient that you import (remove README, Makefile and others...)

**Comment by mfojtik** [comment]
@soltysh LGTM after first look. @bparees can you double check?

**Comment by soltysh** [comment]
@mfojtik @smarterclayton comments addressed. The only remaining stuff is the uids, I'll try to sort that out, if it's still an issue.

**Comment by soltysh** [comment]
[test]

**Comment by smarterclayton** [comment]
LGTM

**Comment by soltysh** [comment]
[merge]

**Comment by mfojtik** [comment]
LGTM [merge]

**Comment by bparees** [comment]
@soltysh please make sure you do a openshift-docs PR to update our recommendations to image authors and anywhere else we discuss STI_SCRIPTS_URL.

**Comment by soltysh** [comment]
@bparees will do once I'll migrate that change into origin.

**Pull request merged**
