### PR TITLE
don't require .git suffix; consolidate validation, empty protocol URL processing (revisited)

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@gabemontero need better PR title ;-)

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
@bparees - tests are now passing in jenkins; prior comments have been incorporated; please see if you are GTM

**Comment by bparees** [comment]
one nit and lgtm.

**Comment by gabemontero** [comment]
nit addressed - thx

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
