### PR TITLE
Fix comment in godepchecker

### PR DESCRIPTION
**Pull request by adambkaplan**
Lets `make verify` pass.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @bparees 
Comment caused `make verify` to fail (w/ golang 1.10)

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@adambkaplan hopefully fixing the test failure here: https://github.com/openshift/source-to-image/pull/869

**Comment by bparees** [comment]
[merge]

**Pull request merged**
