### PR TITLE
ChmodAdapter: don't set hdr.Mode early as subsequent lines still need to read it

### PR DESCRIPTION
**Pull request by jim-minter**
[test]

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, thanks @jim-minter 
[merge]

**Comment by bparees** [comment]
failed windows testing

**Comment by jim-minter** [comment]
[test]

**Comment by jim-minter** [comment]
@bparees I think the change itself is legitimate; the windows testing is failing on this PR (and indeed on master) because of what looks like a change in behaviour or regression in Docker.  The version of Docker has been updated in our CI rhel image from 1.10 to 1.12.  With the new version, there's an issue with the container not seeing stdin close correctly, at least when attaching to a container via the Docker API via TCP+TLS (as our CI system windows testing does).  Running locally over UNIX sockets, it works.  This is causing the CI testing hangs on windows and not linux testing.

I'll look at this further next week, aiming to (a) get a workaround on our CI and (b) deal with the root cause.

**Comment by jim-minter** [comment]
@bparees so if your s2i bump is in a hurry, I'd disable the windows ci and get this PR in and rolled up into your bump. If it can wait, I'll look at this on Mon.

**Comment by bparees** [comment]
i've disabled the windows test (hopefully).
[merge]

**Pull request merged**
