### PR TITLE
Do not attempt to get image ID when no output image specified

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@soltysh @bparees PTAL

**Comment by mfojtik** [comment]
Fixes #235

**Comment by soltysh** [comment]
LGTM [merge]
@ewolinetz can you add int tests for those cases as well, I'm wondering if we do have them for plain s2i builds...

**Comment by ewolinetz** [comment]
@soltysh I can look into that, I am wondering if we should hold off on adding more until the current questions on the PR are answered?

**Pull request merged**
