### PR TITLE
Fixed script path when invoking PostExecute.

### PR DESCRIPTION
**Pull request by soltysh**
@bparees this is initial take to fix the problem with custom `assemble` script inside source repo and `run` pointing to non existent file. This is not ready yet as I need to address  the tests.

### CODE REVIEW

**Comment by bparees** [comment]
will this work for save-artifacts too?

**Comment by soltysh** [comment]
@bparees it will, because the `save-artifacts` is run using the same method as `assemble` (see [here](https://github.com/openshift/source-to-image/blob/master/pkg/build/strategies/sti/sti.go#L298) and [here](https://github.com/openshift/source-to-image/blob/master/pkg/docker/docker.go#L228)). Besides I just double checked it :wink:

**Comment by soltysh** [comment]
@bparees it's ready for your review. The source of the problem was we have a logic around the destination of scripts in `docker.go` but we were missing that in `sti.go#PostExecute`, that's basically what this patch includes. In the mean time
[test]

**Comment by bparees** [comment]
lgtm.  fixes https://github.com/openshift/source-to-image/issues/173

@thoraxe fyi.. after this goes in we'll have to bring it into origin but then overriding run/assemble independently will work.

[merge]

**Comment by soltysh** [comment]
Strange error, as if problem with our vagrant plugin.
re-[merge]

**Comment by thoraxe** [comment]
@bparees step forward!

Do we have a plan for "additive" scripts? EG not having to override the entire script with a copy of the original?

**Comment by bparees** [comment]
We're still carrying an open issue for that.

Ben Parees | OpenShift

**Comment by soltysh** [comment]
[merge] 

again, as previous one wasn't picked up

**Pull request merged**
