### PR TITLE
bump(github.com/docker/docker): 4f3616fb1c112e206b88cb7a9922bf49067a7756 

### PR DESCRIPTION
**Pull request by soltysh**
@bparees the PR I told you about yesterday which is coming from the rebase
@mfojtik fyi

### CODE REVIEW

**Comment by soltysh** [comment]
Btw. I've copied over here the scripts for godep restore and save, so this is similar to the flow we have in origin. And hopefully will be repeatable by others, that's why there are some extra packages.

**Comment by bparees** [comment]
lgtm
[merge]

**Comment by bparees** [comment]
@soltysh you're going to have to work out some windows issues/more dep bumping in these deps:

```
Performing source-to-image build...
go version go1.7.1 windows/amd64
++ Building go targets for windows/amd64: cmd/s2i
_output\local\go\src\github.com\openshift\source-to-image\vendor\github.com\Sirupsen\logrus\text_formatter.go:13:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	C:\cygwin\data\src\github.com\openshift\source-to-image\_output\local\go\src\github.com\openshift\source-to-image\vendor\golang.org\x\crypto\ssh\terminal (vendor tree)
	C:\Go\src\golang.org\x\crypto\ssh\terminal (from $GOROOT)
	C:\cygwin\data\src\github.com\openshift\source-to-image\_output\local\go\src\golang.org\x\crypto\ssh\terminal (from $GOPATH)
	C:\cygwin\data\src\github.com\openshift\source-to-image\vendor\src\golang.org\x\crypto\ssh\terminal
```

**Comment by soltysh** [comment]
Sigh... and I was hoping this will be simple ;) Anyway we should be able to straight this out with all this :)

**Comment by mfojtik** [comment]
also `github.com\Sirupsen\logrus` should be `github.com\sirupsen\logrus` ? i thought we had a conflict in case for that dep

**Comment by soltysh** [comment]
Rebased, I can't see `Sirupsen/logrus' in vendor, anywhere. Let's see what will happen now.

**Comment by soltysh** [comment]
There were two problems:

1. old Azure/go-ansiterm which relied on Sirupsen/logrus instead of the lowercase counterpart
2. missing golang.org/x/crypto/ssh/terminal

With the two in, it should be good now.

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
I removed the merge tag, so that I can fully test it.

**Comment by soltysh** [comment]
Perfect, that's what I was hoping for.

[merge]

**Pull request merged**
