### PR TITLE
Update core dependencies (CVE fixes)

### PR DESCRIPTION
**Pull request by sayan-biswas**
Changes:
- Update docker dependency
- Adjust code for deprecated docker APIs

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

Dependency updates and code changes look good!

**Comment by adambkaplan** [comment]
/approve

Changing this to an approve - we should bring in the ubi8 change and the dependency updates

/lgtm cancel

Looks like the switch to go 1.21 is not done right/breaking CI.

**Comment by sayan-biswas** [comment]
/override "Red Hat Konflux / source-to-image-enterprise-contract / source-to-image"

**Review by ramessesii2 — APPROVED** [review]
/lgtm

**Pull request merged**
